name: AllBranchesCI
on:    
  push:    
    branches:    
      - '*'    
jobs:    
  build:    
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout OWL from github
        uses: actions/checkout@v2
      - name: Make barebone, stand-alone OWL  
        run: make owl
