name: AllBranchesCI
on:    
  push:    
    branches:    
      - '*'    
jobs:    
  build:    
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout OWL from github
        uses: actions/checkout@v2
      - name: Link to the Linux architecture file
        run:  rm architecture.inc; ln -s architecture/generic_linux architecture.inc
      - name: Make barebone, stand-alone OWL
        run: make owl
